version: '3'
services:
  api:
    container_name: payment_api
    build: .
    image: microservice/payment:latest
    ports:
      - 9090:9090
    volumes:
      - ./api:/go/src/app
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: payment_db
    ports:
      - '27100:27017'